<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SHREETAMA" failures="2" tests="12" name="com.LibraryManagement.cucumber.Runner.RunnerTest" time="99.695" errors="0" timestamp="2025-07-29T09:22:27 IST" skipped="0">
  <testcase classname="com.LibraryManagement.cucumber.Runner.RunnerTest" name="runScenario" time="8.944"/>
  <testcase classname="com.LibraryManagement.cucumber.Runner.RunnerTest" name="runScenario" time="10.335">
    <failure message="Card number field is not reset expected [] but found [LCN_004]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Card number field is not reset expected [] but found [LCN_004]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.LibraryManagement.cucumber.stepDefinition.MembershipSteps.verifyFieldReset(MembershipSteps.java:151)
at ✽.Card number field should be reset(file:///C:/Second_Script/Sprint-2/Sprint_2/src/test/java/com/LibraryManagement/cucumber/features/MemberShip.feature:88)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.LibraryManagement.cucumber.Runner.RunnerTest" name="runScenario" time="11.203">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.LibraryManagement.cucumber.stepDefinition.MembershipSteps.duplicateErrorMessage(MembershipSteps.java:164)
at ✽.Error message should appear for duplicate number(file:///C:/Second_Script/Sprint-2/Sprint_2/src/test/java/com/LibraryManagement/cucumber/features/MemberShip.feature:102)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.LibraryManagement.cucumber.Runner.RunnerTest" name="runScenario" time="7.483"/>
  <testcase classname="com.LibraryManagement.cucumber.Runner.RunnerTest" name="runScenario" time="7.274"/>
  <testcase classname="com.LibraryManagement.cucumber.Runner.RunnerTest" name="runScenario" time="8.968"/>
  <testcase classname="com.LibraryManagement.cucumber.Runner.RunnerTest" name="runScenario" time="5.371"/>
  <testcase classname="com.LibraryManagement.cucumber.Runner.RunnerTest" name="runScenario" time="10.155"/>
  <testcase classname="com.LibraryManagement.cucumber.Runner.RunnerTest" name="runScenario" time="7.110"/>
  <testcase classname="com.LibraryManagement.cucumber.Runner.RunnerTest" name="runScenario" time="9.028"/>
  <testcase classname="com.LibraryManagement.cucumber.Runner.RunnerTest" name="runScenario" time="6.270"/>
  <testcase classname="com.LibraryManagement.cucumber.Runner.RunnerTest" name="runScenario" time="7.554"/>
</testsuite> <!-- com.LibraryManagement.cucumber.Runner.RunnerTest -->
